require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Tran. As you add validations to Tran, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all trans as @trans" do
      transcription = Tran.create! valid_attributes
      get :index
      assigns(:transcriptions).should eq([transcription])
    end
  end

  describe "GET show" do
    it "assigns the requested transcription as @transcription" do
      transcription = Tran.create! valid_attributes
      get :show, :id => transcription.id
      assigns(:transcription).should eq(transcription)
    end
  end

  describe "GET new" do
    before(:each) do
      @video_segment = Factory.create(:video_segment)
    end

    it "assigns a new transcription as @transcription" do
      get :new, :video_segment_id => @video_segment.id
      assigns(:transcription).should be_a_new(Tran)
    end
  end

  describe "GET edit" do
    it "assigns the requested transcription as @transcription" do
      transcription = Tran.create! valid_attributes
      get :edit, :id => transcription.id
      assigns(:transcription).should eq(transcription)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tran" do
        expect {
          post :create, :transcription => valid_attributes
        }.to change(Tran, :count).by(1)
      end

      it "assigns a newly created transcription as @transcription" do
        post :create, :transcription => valid_attributes
        assigns(:transcription).should be_a(Tran)
        assigns(:transcription).should be_persisted
      end

      it "redirects to the created transcription" do
        post :create, :transcription => valid_attributes
        response.should redirect_to(Tran.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transcription as @transcription" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tran.any_instance.stub(:save).and_return(false)
        post :create, :transcription => {}
        assigns(:transcription).should be_a_new(Tran)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tran.any_instance.stub(:save).and_return(false)
        post :create, :transcription => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transcription" do
        transcription = Tran.create! valid_attributes
        # Assuming there are no other trans in the database, this
        # specifies that the Tran created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tran.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => transcription.id, :transcription => {'these' => 'params'}
      end

      it "assigns the requested transcription as @transcription" do
        transcription = Tran.create! valid_attributes
        put :update, :id => transcription.id, :transcription => valid_attributes
        assigns(:transcription).should eq(transcription)
      end

      it "redirects to the transcription" do
        transcription = Tran.create! valid_attributes
        put :update, :id => transcription.id, :transcription => valid_attributes
        response.should redirect_to(transcription)
      end
    end

    describe "with invalid params" do
      it "assigns the transcription as @transcription" do
        transcription = Tran.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tran.any_instance.stub(:save).and_return(false)
        put :update, :id => transcription.id, :transcription => {}
        assigns(:transcription).should eq(transcription)
      end

      it "re-renders the 'edit' template" do
        transcription = Tran.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tran.any_instance.stub(:save).and_return(false)
        put :update, :id => transcription.id, :transcription => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transcription" do
      transcription = Tran.create! valid_attributes
      expect {
        delete :destroy, :id => transcription.id
      }.to change(Tran, :count).by(-1)
    end

    it "redirects to the trans list" do
      transcription = Tran.create! valid_attributes
      delete :destroy, :id => transcription.id
      response.should redirect_to(trans_url)
    end
  end

end
